### PR TITLE
petal comb filter

### PR DESCRIPTION
**Pull request by beserge**

### CODE REVIEW

**Comment by stephenhensley** [comment]
QuickNotes:

* So strangely, the Comp module's SetFreq actually sets the time in seconds.. So the mapping for the controls was crazy and would crash or not make sound.
* The Comb filter doesn't seem to like being modulated much (probably worth you messing with a similar example on the Patch for easier testing on your end while this gets worked out). Could be something with knobs or comb filters, as well.
* when setting the amplitude of the LFO, instead of using a fixed `x10` multiplier, which could be out of range or really extreme for certain settings. you can use the actual frequency as a scalar, and then you'll definitely want to clamp somewhere close to zero if the comb filter breaks at frequency 0 (and/or add that clamping to the comb if it breaks it).
* Consistency of control usage would be nice. I don't mind the UpdateControls() function, but if you have to mix controls inside the audio loop, the rest might as well be there as well so a reader doesn't have to jump around as much. Alternatively read all of your AnalogControls/Parameters in the UpdateControls, and then filter them at audio rate or something in the audio callback.
    * Similarly, `UpdateAnalogControls` should only be used if you aren't using Parameters (which calls process) or don't want to deal with the Process calls themselves. After Process has been called once at the initialized samplerate, the `Value` function should be used instead to update the value without changing the filter response, etc. 
    * On the same note there are some Parameters being used, and some transforms being done on AnalogControls. I personally rarely use the parameter class, but if you want to use it I think it should be consistently used.
* add `petal.UpdateLeds();` after you set the FootswitchLed to actually write swap the DMA buffers and transmit the new data.
* The CombFreq works pretty well between like 500us and 100ms or so ). Equivalent to  (10Hz - 2kHz) with Log scaling
    * When updating that make sure the delay will accommodate the lowest frequency (including what the LFO is doing.


Related: We should just fix the comb so it has SetFreq (which does exactly what it does now but to `1.f / inputvalue`), and add SetPeriod for seconds.

**Comment by beserge** [comment]
Depends on changes to comb in DaisySP

**Comment by corellmichael** [comment]
### Notes

- Switch Toggle is opposite right now.

- Clicks are fairly noticeable in my set up, especially when the LFO amp is up.

- seems like some changes need to be made to the DaisySP comb to make it more comby.

**Comment by corellmichael** [comment]
[Redo all example diagrams in new style](https://trello.com/c/IS6FeGan/60-redo-all-example-diagrams-in-new-style)

**Comment by beserge** [comment]
[Petal Comb Filter](https://trello.com/c/eIUxMmhp/62-petal-comb-filter)

**Comment by corellmichael** [comment]
# Notes

- Comb sounds more comby, which is great.
- Noise still occurs when adjusting Comb Frequency, both with the knob and LFO. If there is a way to smooth out the Comb frequency that would be great.
- LED sequence is cool, but a bit much. Either slow it down or use it as a visual cue for the LFO rate.

**Comment by corellmichael** [comment]
# Notes

- significantly less zipper, but still kind of there. Maybe needs peer review to determine whether or not it needs further de-zipping.

-  everything else is working great.

**Comment by stephenhensley** [comment]
@corellmichael just realized you were probably building this on your end as well. Which means you should be able to just pull the latest version of the libs, and rerun as is.

**Pull request merged**
