### PR TITLE
Add simple oscillator with built in envelope

### PR DESCRIPTION
**Pull request by chrisfromwork**
I have been an active viewer/contributor to the [BasementState twitch stream](https://www.twitch.tv/basementstate). This oscillator is intended to be used in a tutorial stream sometime in the next couple of months.

### CODE REVIEW

**Comment by stephenhensley** [comment]
Just gave it a quick test and it works as expected. 

I can merge as-is, but I do suggest adjusting your envelope `Trigger` function to not reset the phase of the envelope to 0, and instead enter the attack stage from the current phase. Reason being that retriggering during an envelope stage the envelope jumps to 0 creating an audible click.

Having the trigger simply reenter the attack stage would have the following effects: incoming triggers during the attack would be ignored, triggers during the decay phase would begin to rise from the current level instead of 0, and triggers received while the envelope are idle would work the same as they currently do.

**Comment by chrisfromwork** [comment]
@stephenhensley I've noticed this sound and thats a great suggestion. I'll look into updating this code this weekend and will push more commits

**Comment by chrisfromwork** [comment]
@stephenhensley  i think it should be good now

**Comment by stephenhensley** [comment]
@chrisfromwork great! should be able to give it a quick within the next day or so and get it merged. I don't expect any other issues since it was such a minimal change.

**Comment by chrisfromwork** [comment]
@stephenhensley is there anything else i can do to help get this merged?

**Comment by stephenhensley** [comment]
Ah, sorry. My bad for the delay. I just gave it a test, and a few things still stand out. 

1. Outputs 2-4 are heavily distorted sound. You can resolve this by writing those channels to zero.
2. With the change you made, which does prevent clicks during when resetting in the attack stage, the envelope now seems to skip the attack phase and jump back to the top of the decay stage when retriggered during that stage. This creates another pop sound. I suspect that this was happening before as well, or was at least hidden by resetting your phase increment.
3. Your README describes clicking the encoder for curve control mode, which does not seem to work.

**Comment by stephenhensley** [comment]
I totally meant to test this and merge it before doing the AudioHandle typename change, but alas I forgot.

Anyway, I retested it with one change so it works with the latest libDaisy:

Basically,
`void Callback(float** in, float**out, size_t size)`
will become:
`void Callback(AudioHandle::InputBuffer, AudioHandle::OutputBuffer, size_t size)`

And it works great. I love being able to trigger it with the encoder. Sorry again for all the delays.

I'll just merge this as-is and make the typename change separately to spare you the trouble.

Thanks for the contribution! Look forward to seeing the video for Patchwerks when you get around to it! :)

**Pull request merged**
