### PR TITLE
Patch template

### PR DESCRIPTION
**Pull request by andrewikenberry**

### CODE REVIEW

**Comment by stephenhensley** [comment]
First pass notes:

* `stm32h7xx_hal_conf.h` and `system_stm32h7xx.c` are no longer needed and should be deleted.
* STM32H750IB_flash.lds is no longer needed, and should be deleted.
    * if the `vcxproj` or `vcxproj-filters` reference it, the paths(s) should be updated to the `libdaisy/core` version.
* The VS/VGDB files (`*.vgdbsettings`, `*.vcxproj*`, `stm32.*` should be moved into a vs/ folder, though this will require editing all of the relevant paths within those files. So I can take care of that if you don't want to go through it all. (If you do, don't name it the directory `.vs` as that is an auto-generated hidden directory, and ignored by `.gitignore`
* README is out of date and is for PluckEcho example.

As discussed earlier, there could be an argument made for moving the template projects to `utils/templates` or somewhere that the copy/new project scripts can reach them without users thinking they can easily copy the entire folder structure themselves (since the vscode and vs/vgdb integration requires quite a bit of path mangling).

Since the counter-argument is having easy access to good starter code -- the program (being only 30 lines) could easily be added to the README, or elsewhere within our documentation (even in the getting started guide). 

Open to either, but definitely worth discussing since this will currently be added to the Web programmer as a second 'bypass/passthru' example, which we don't necessarily need there.

**Comment by andrewikenberry** [comment]
[Make template cpp files for each platform](https://trello.com/c/65l18tv1/4274-make-template-cpp-files-for-each-platform)

**Comment by andrewikenberry** [comment]
- Regarding the VS folder, shouldn't it be called vs/ ? I'm not sure why you mention the hidden .vs directory

-  Regarding the location / web programmer, I agree. Let's move it to utils/. We can document in the readme / documentation where to find the template. Worth noting not every platform has a passthrough example yet so we should remedy that situation as well.

**Comment by stephenhensley** [comment]
closing because the work is going to continue in #127 -- your branch has been merged there and should now be safe to delete.

**Pull request closed without merging**
