### PR TITLE
Distortion for petal

### PR DESCRIPTION
**Pull request by beserge**
Right now there's a hard clip in series with a soft clip. It might be better to seperate them out into two distortion modes, or remove one of them.

### CODE REVIEW

**Comment by stephenhensley** [comment]
Quick Notes:
* Needs bypass button(s)
    * Could actually use two buttons, one for each distortion.
* Add a separate pregain for each stage of the distortion
* Adjust existing gain so that its a bit more subtle at the lowest settings (maybe like 1.2 as a starting point instead of 10). I like how aggressive it gets, but its too much too soon.
* Make it stereo, especially since this is such a small example, it won't make it harder to follow if its stereo. having each channel handled in a loop might actually make the existing callback a little easier for people to follow.

One other thing.  I don't want to go back and do this for the other examples that don't make use of the encoder, but the LED ring should probably always do _something_ in the same way that we deal with the OLED, otherwise the module can look dead.

If you don't want to just use a static color for the whole ring (which is fine), you could abstract the Ring portion of the VegasMode function to its own function in DaisyPetal that doesn't actually update the LEDs, so it can be used along side other LED setting code.

**Comment by corellmichael** [comment]
# Notes

. Switches do not toggle distortions on/off. Switch LED's do not light up.

**Comment by corellmichael** [comment]
[Distortion Petal Example](https://trello.com/c/qqMS55nV/57-distortion-petal-example)

**Comment by corellmichael** [comment]
# Notes (Update 10-27-20)

. Switch LEDs now light up, but Switches do not toggle distortions.

. Distortions both sound good, but feedback occurs relatively early in the knobs positions, only when using both distortions. For example, when either distortion is all the way up, the other distortion cannot be more than 1/4 turned before constant feedback occurs. Not sure if this is a necessary fix, but if it can be moderately alleviated with negative feedback or some other application it might be worth it.

**Comment by beserge** [comment]
There's no feedback on my end, and the code doesn't actually include any feedback, so I'm wondering what's up with that.

**Comment by stephenhensley** [comment]
@beserge does the frequency of the 'feedback' change with the audio block size? (Would be inversely proportional -- i.e. doubling the block size would halve the frequency)

**Comment by beserge** [comment]
Ok, so here's what I've found.
The "feedback" only occurs when an input is unused, and is therefore floating.
So, the input is bouncing around randomly, and what we're hearing is that signal amplified and clipped.

I'm not sure if there's a way to fix this, maybe if the inputs have the switch set up, I could use that to detect if an input is plugged in.

**Pull request merged**
