### PR TITLE
euclidean drum sequencer

### PR DESCRIPTION
**Pull request by beserge**
Won't fill out to full pattern density for some reason.

### CODE REVIEW

**Comment by stephenhensley** [comment]
So this one is a bit more complex, I'll have to take some time to look at it a bit more (especially to see if I can spot why it won't go to full density).

But first pass thoughts are:
* Super cool example
* Interface is a bit difficult at first, but pretty good when you get used to it
* WTF is a Bjork haha (short google makes it seem like a fast false positive check of some sort?)
* This one sounds like its clipping a lot more or something (the snare seems really distorted all the time compared to in the seed drum example).

**Comment by beserge** [comment]
Full density bug is fixed.

**Comment by stephenhensley** [comment]
It looks like you're up to date, but its not quite sync'd with master (300+ changed files) if you could rebase so that its just the relevant files that would be great.

**Comment by beserge** [comment]
Rebased! 👍

**Comment by stephenhensley** [comment]
Hmm, your euclid thing is awesome, but idk if the less than half density patterns are accurate or not.. (not sure that I care in this case), but seems weird.

for example with 16 steps, and 2 enabled I'm getting:
```
x x x x | x x x x | x x x x | x x x x
! - - -   ! - - -   - - - -   - - - -
```
instead of what I'd expect which is:
```
x x x x | x x x x | x x x x | x x x x
! - - -   - - - -   ! - - -   - - - -
```
so on a lot of the low density patterns you end up with a lot of silence at the end instead of the best-approximate distribution.

----

Just a few other notes:

Patterns less than 32 steps long can't have their full pattern density (one note missing per loop

I think its nice to be able to mute one of the drums by setting is length to 0, but I don't think the pattern density should go to empty. It gives you two opportunities to mute your drum, and it can be easy to lose track between the two channels and have to just turn every knob up. Not the biggest deal, just a small quality of life improvement.

**Comment by stephenhensley** [comment]
I think some of the patterns are still funky, but it works and feels like euclidean patterns.

**Pull request merged**
