### PR TITLE
Phaser effect for daisy petal

### PR DESCRIPTION
**Pull request by beserge**

### CODE REVIEW

**Comment by corellmichael** [comment]
# Notes

. Phaser is acting more like a Tremolo with a sawtooth ramp on the second audio signal, as oppose to affecting the sound with all-pass filters.

. Switch 1 does not toggle effect on/off. LED does not turn on either.

**Comment by corellmichael** [comment]
[Phaser Petal Example](https://trello.com/c/ttvQuwel/56-phaser-petal-example)

**Comment by stephenhensley** [comment]
So just giving this a quick look I noticed a few things that would definitely make it not work correctly.

The big one is that you're feeding the audio into the filters in parallel (each filter has the dry signal as its input instead of the previous filters. That said you only have it set to one filter right now, and I don't think you'll get the classic phaser sound until there are at least 6-8 filters (there are about half as many peaks created in the signal as there are filter stages).

Once that's done you'll probably want to remove a lot of the attenuation you have from adding your parallel filters together, and such. Pretty much the only thing you should have to scale is the mix between the dry signal and the post-depth, though the block diagrams I've seen has the end of chain as a simple sum between the dry and wet.

Also, the allpass filter in our library is a little confusing in that it uses terms like looptime and revtime to control the delay size and frequency respectively. So you may want to be modulating revtime instead of looptime (maybe). Alternatively we could make a much simpler all pass.

Phaser being a pretty common effect we'll probably want to make a module out of the phaser effect. So if you could reorganize the code to be a bit more portable in that way it would be nice, as well.

All that said, if just switching the parallel filtering to series, and updating the number of filters doesn't start to make it sound like a phaser, then maybe we table this one and work on the other examples for a bit. As it would seem like there's an issue with one of the dsp blocks and not the example itself.

**Comment by beserge** [comment]
out of date, moving to new phase module

**Pull request closed without merging**
