### PR TITLE
FIR filter example

### PR DESCRIPTION
**Pull request by AXP**
### Simple FIR filter module

Two implementations are provided, one is generic and portable, another is based on ARM CMSIS DSP implementation. Since the implementation is fully enclosed in the header file, it is up to the user to decide which implementation to use and link necessary CMSIS objects. This allows DaisySP to maintain its portability.
Both are wrapped in equivalent API's and care is taken for the wrapping to be maximally efficient.
ARM-specific version is exposed only on compatible platforms and can be optionally disabled.
The best implementation is aliased as FIR class to simplify instantiation.

Supports both static internal and user-provided memory allocation.

### Unit test
The module is accompanied by unit test/benchmark (DaisySP/tests/fir)
It may be executed on DaisyPod (default), DaisySeed (simple variable change) via Makefile, with or without ARM CMSIS DSP support (configured inside the Makefile) but also via VisualStudio project, both with VisualGDB on same DaisyPod/DaisySeed targets or directly on a PC (x64 target). In the PC case, ARM-optimized version is of course disabled and the result verification is only carried out between static and user memory allocation models.

### Example of usage
The module is accompanied by usage example (DaisyExamples/seed/fir)
Runs on Daisy Seed, uses LFO to sweep a low-pass filter on a white noise generator. 
Whether the ARM or generic version of FIR implementation is used is governed by the following Makefile setting:
C_DEFS += -DUSE_ARM_DSP
VisualGDB build/execution is also supported/tested, although only Release build fits into target memory

### LibDaisy changes
- a few new lines in .gitignore, removed redundant ones
- Added x64 target to Visual Studio project. It is required by the VS solution, even if this project is excluded from build
- static_assert usage is updated to be compatible with all compilers

As an experiment, this is a single DaisyExamples pull request that supposedly includes both DaisySP and libDaisy submodules.

### CODE REVIEW

**Comment by stephenhensley** [comment]
Nice! I should be able to review it this weekend or early next week. I noticed the DaisySP PR has not yet been converted from Draft. I'm assuming I should wait for that before reviewing both since they'll rely on each other?

**Comment by AXP** [comment]
The way it looks to me is that this PR includes all files regardless of what I have in the draft PR's in individual repo's. If it really works that way, that would improve atomicity of the changes, but make it harder to track/rollback changes.
Let me know whether it works that way or if I'm mistaken. In that case I will flip the draft switch on the other ones.

**Comment by stephenhensley** [comment]
Alright! Finally had a chance to check this out last night/this morning.

Everything seems solid, and I absolutely _love_ the test program. Very cool to see some validation, and benchmarking within the DaisySP hierarchy.

The submodule checkout failed on my end, but I suspect that's because the refs had changed when I merged the Phaser PR. In any case, it was still faster because it gave me the commit refs to checkout inline without me having to go through the browser to find them. So this workfllow works fine for the future.  That said, I think once merged, it wouldn't merge your attached PRs, it would just point the refs at your fork.

The only issue I saw was specific to the Debug build of the test program  where I got the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		[Clang IntelliSense] Error: 'C:/Users/shensley/Desktop/DaisyExamples/DaisySP/tests/fir/vs/stm32h7xx.h' file not found			1	
```

**Comment by AXP** [comment]
Thanks for the pointer, the intelliSense error is not fixed (well, I believe) by using absolute path for the force-included header.
There were also indeed conflicts in the submodule commit id's. 
Please again to see that I didn't break the stuff you merged last.

Also enabled individual repo PR's:
https://github.com/electro-smith/libDaisy/pull/310
https://github.com/electro-smith/DaisySP/pull/147

**Comment by stephenhensley** [comment]
Wonderful. Everything checks out on my end.  This time, git appeared to fetch the submodule commits, but didn't actively check them out (I tried on a fresh clone of the repo this time as well). Guess we'll see what happens when I merge, but I suspect I'll still have to go merge the other PRs as well.

In general, I'm not the biggest fan to restricting software to a specific OS, especially windows. But it looks like this can pretty easily transplant to other OSes once there's time and reason to do so (CI running the tests, etc.). It helps that the test can actually be run on the daisy hardware as well.

Seems like despite things being split across three repos, everything has stayed pretty atomic, and there haven't been many conflicts in general.

Thanks for the huge contribution, and for jump starting a test framework. Very grateful for your work!

**Comment by stephenhensley** [comment]
Interestingly, after merging, the submodule refs on DaisyExamples master branch were pointing to your fork's commits. So it seems like it sort of worked how we expected. And once #124 is fixed and the build all script actually fails when there's an error this would have prevented failures due to unmerged content on the other repos. So 👍

**Pull request merged**
