### PR TITLE
Add Field port of Nimbus

### PR DESCRIPTION
**Pull request by gregornoriskin**
Other than Nimbus.cpp and README.md are identical to Ben's original.

### CODE REVIEW

**Comment by beserge** [comment]
OK just tried compiling things over here. With the latest version of libdaisy it overflowed by about 9kb. Does the same happen on your machine?

**Comment by stephenhensley** [comment]
If you add `OPT=-Os` to the Makefile it should compile with room to spare.

**Comment by beserge** [comment]
Yep that fixed it. Really awesome work, had a lot of fun testing it! If you can add that flag to the makefile I say it's good to be merged.

Nice work on the readme as well, very thorough.

**Comment by stephenhensley** [comment]
I just gave it a whirl, too. Very cool adjustments to the GUI!

So if you can just update the Makefile with that flag above we can get this merged in!

Thanks for the fantastic contribution!

**Comment by gregornoriskin** [comment]
> Yep that fixed it. Really awesome work, had a lot of fun testing it!
> I noticed the spread control stops working when Shift is selected.
> 
> If you fix those two bugs I say we're good to merge.
> 
> Nice work on the readme btw, very thorough.

By design. Because the Shift is a toggle, none of the unshifted parameters will change when it is engaged.

**Comment by stephenhensley** [comment]
I don't love that the feedback param changes along with reverb when toggling shift on/off, but its acceptable for now. Especially since it's noted in the README.

I think we'll be revamping the original Nimbus, (and can probably update this one at the same time) to use the new UI framework introduced recently in libDaisy soon. So we can address small things like that (and any other UI related feedback we get) when we go through reworking it.

**Pull request merged**
